name: CRUD CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['20.15.0']

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Build the code 
        run: npm run build

      - name: Zip the build artifacts
        run: zip -r build.zip build

      - name: Upload build artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip
